[package]
name = "bogon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnetwork = { git = "https://github.com/achanda/ipnetwork", rev = "068959e2c44fb4b6815666047d4162de86edbd4a", default-features = false }

[build-dependencies]
csv = "1.3.0"
ipnetwork = { git = "https://github.com/achanda/ipnetwork", rev = "068959e2c44fb4b6815666047d4162de86edbd4a" }
serde = { version = "1.0.199", features = ["derive"] }
