[package]
name = "bogon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ipnetwork = { version = "0.20.0", default-features = false }
# ipnetwork = { git = "https://github.com/achanda/ipnetwork", rev = "a1966d40898faba1136a2e75d85a8602a5a7e7f3", default-features = false }
ipnetwork = { git = "https://github.com/Alextopher/ipnetwork.git", branch = "ipv6", default-features = false }

[build-dependencies]
csv = "1.3.0"
# ipnetwork = { version = "0.20.0", default-features = false }
ipnetwork = { git = "https://github.com/Alextopher/ipnetwork.git", branch = "ipv6" }
serde = { version = "1.0.199", features = ["derive"] }
