name: Rust Feature Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        feature: ["" , "--features download"]
        
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Lint with ${{ matrix.feature }}
        run: cargo clippy --verbose ${{ matrix.feature }} -- -D warnings

  build:
    needs: lint

    strategy:
      matrix:
        rust: [stable, beta, nightly]
        feature: ["" , "--features download"]
        
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install dependencies
        run: cargo fetch

      - name: Build with ${{ matrix.feature }}
        run: cargo build --verbose ${{ matrix.feature }} 
        
      - name: Test with ${{ matrix.feature }}
        run: cargo test --verbose ${{ matrix.feature }}
